build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    coverage:
      tests:
        override:
          - command: npm test
filter:
  excluded_paths:
    - "test/"
    - "serviceWorker.js"
